# jason-ros-course-wesaac2024
:toc: right
:author: Maiquel de Brito
:date: July 2023
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:


Tutorial on Jason-ROS - WESAAC 2024

== Preliminaries
=== Running ROS
This course requires to install ROS (either version 1 or 2) and the turtlesim simulator. 
As alternative, use the following commando to run a docker container with all the requirements installed.
----
sudo docker run -d --rm --net=ros --env="DISPLAY_WIDTH=3000" --env="DISPLAY_HEIGHT=1800" --env="RUN_XTERM=no" --name=novnc -p=8080:8080 theasp/novnc:latest  && \
sudo docker run -d --net=ros --name roscore --rm osrf/ros:noetic-desktop-full roscore && \
sudo docker run -it --net=ros --env="DISPLAY=novnc:0.0" --env="ROS_MASTER_URI=http://roscore:11311" --rm --name embedded-mas-example -p9090:9090 maiquelb/embedded-mas-ros2:0.5 /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 run turtlesim turtlesim_node" & \
(until sudo docker exec embedded-mas-example /bin/bash -c "echo '***** ROS container is ready *****'" 2>/dev/null; do echo "waiting for ROS container to start..."; sleep 1; done  && \
sudo docker exec  embedded-mas-example /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml")
----
When the container is launched, go to link:http://localhost:8080/vnc.html[`http://localhost:8080/vnc.html`] to inspect the simulation.

== Part 1: Introduction to ROS 

=== Task 1.1: Understanding ROS Topics
* Exercise 1.1.1. The command shown below lists the avaliable topics and the data type that they record. Type it and observe the output.
----
ros2 topic list -t
----

* Exercise 1.1.2. ROS data type (also known as message types) may record complex data structures. Use the command below to check the data structure of the different data types. Replace `[data type]` by the data type to be ckecked.
----
ros2 interface show [data type]
----

* Exercise 1.1.3. Type the following command in a shell and observe the behaviour of the turtle:
----
ros2 topic pub -1 /turtle1/cmd_vel geometry_msgs/msg/Twist  "{linear: {x: 1.0, y: 1.0, z: 1.0}, angular: {x: 0.0, y: 0.0, z: 0.0}} "
----

=== Task 1.2: ROS Services
* Exercise 1.2.1. The command shown below lists the avaliable service and the data type that they request/return. Type it and observe the output.
----
ros2 service list -t
----

* Exercise 1.2.2. ROS service type define the structure of request and response data. Use the command below to check the data structure of the different service types. Replace `[service type]` by the data type to be ckecked. As a suggestion, check the type of the services `/rosapi/list_parameters` and `/turtle1/set_pen`. What are the inputs and outputs?
----
ros2 interface show [service type]
----

* Exercise 1.2.3. Type the following command in a shell and observe the behaviour of the turtle:
----
ros2 service call /turtle1/teleport_absolute turtlesim/srv/TeleportAbsolute "{x: 5.0, y: 5.0, theta: 1}"
----


== Part 2. Introduction to Jason

=== Task 2.1: Run the first JaCaMo application

Clone the repository at (https://github.com/maiquelb/jacamo-wesaac2023). Open the folder link:hands-on/lab1[`hands-on/lab1`] with the Visual Studio Code (or access it in the terminal).  Then, run the project by typing the command below in the terminal:

----
jacamo agents_intro.jcm 
----



=== Task 2.2: Reading and understanding agent programs

* Exercise 2.2.1: open the JaCaMo application file (link:hands-on/lab1/agents_intro.jcm[`agents_intro.jcm`]) and the personal assistant agent code (file link:hands-on/lab1/src/agt/personal_assistant.asl[`src/agt/personal_assistant.asl`]). Read the files and identify the beliefs, goals, and plans. Try to map the program to the observed behavior. 

* Exercise 2.2.2: open the link:http://localhost:3272/[_mind inspector_] for the agents `bob` and `marie`. Compare the beliefs there with those identified in the program. Are they the same? Are they represented the same way? 

* Exercise 2.2.3: observe the plan in lines 13--14 of the personal assistant agent code (file link:hands-on/lab1/src/agt/personal_assistant.asl[`src/agt/personal_assistant.asl`]). What is the difference between this plan and the other ones?

* Exercise 2.2.4: type the command below, replacing `<agent_id>` by the identifier of an agent (either `bob` or `marie`). Observe the behaviour of the agent. Open the link:http://localhost:3272/[_mind inspector_]  and check whether the belief base of the agent has changed after running this command.

----
curl --request POST 'http://127.0.1.1:8080/agents/<agent_id>/command' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'c=-+day_of_week(sunday)'
----

=== Task 2.3: Extending the agent program
* Exercise 2.3.1: make the agent `bob` to inform the current date using the plan `inform_date`. The other agents must not give this information.

* Exercise 2.3.2: add a new personal assistant agent to the system. This agent should greet in portuguese ("Bom dia.").

* Exercise 2.3.3: set the language of bob to japanese without adding any plan. Run the system and observe the output. Handle exceptions if needed.


==== Questons:
* Where to the beliefs come from?
* Where are the actions implemented?

=== Task 2.1 Understanting and programming beliefs

== Part 3: Introduction to Jason-ROS

== Part 4: Advancing on Jason-ROS

=== Implementing complex behaviours
=== Programming multi-robot systems
=== Customizing internal actions
