# jason-ros-course-wesaac2024
:toc: right
:author: Maiquel de Brito
:date: July 2023
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:


Tutorial on Jason-ROS - WESAAC 2024

== Preliminaries
=== Running ROS
This course requires to install ROS (either version 1 or 2) and the link:http://wiki.ros.org/turtlesim[turtlesim simulator]. 
As alternative, use the following commando to run a docker container with all the requirements installed.
----
sudo docker run -d --rm --net=ros --env="DISPLAY_WIDTH=3000" --env="DISPLAY_HEIGHT=1800" --env="RUN_XTERM=no" --name=novnc -p=8080:8080 theasp/novnc:latest  && \
sudo docker run -d --net=ros --name roscore --rm osrf/ros:noetic-desktop-full roscore && \
sudo docker run -it --net=ros --env="DISPLAY=novnc:0.0" --env="ROS_MASTER_URI=http://roscore:11311" --rm --name embedded-mas-example -p9090:9090 maiquelb/embedded-mas-ros2:0.5 /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 run turtlesim turtlesim_node" & \
(until sudo docker exec embedded-mas-example /bin/bash -c "echo '***** ROS container is ready *****'" 2>/dev/null; do echo "waiting for ROS container to start..."; sleep 1; done  && \
sudo docker exec  embedded-mas-example /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml")
----

----
( sudo docker ps -q --filter "name=novnc" | grep -q . && sudo docker stop novnc || true) &&\
( sudo docker ps -q --filter "name=turtles_example" | grep -q . && sudo docker stop turtles_example || true) &&\
( sudo docker network ls --filter name=^ros$ --format="{{ .Name }}" | grep -q "^ros$" || sudo docker network create ros ) &&\
sudo docker run -d --rm --net=ros --env="DISPLAY_WIDTH=3000" --env="DISPLAY_HEIGHT=1800" --env="RUN_XTERM=no" --name=novnc -p=8080:8080 theasp/novnc:latest  && \
sleep 2 &&\
sudo docker run -d --name turtles_example --rm --net=ros --env="DISPLAY=novnc:0.0" --env="ROS_MASTER_URI=http://localhost:11311" -p11311:11311 -p9090:9090 maiquelb/embedded-mas-ros2:0.5 /bin/bash -c '\
 ( \
  ( source /opt/ros/humble/setup.bash && ros2 run  turtlesim turtlesim_node) &\ 
  ( source /opt/ros/humble/setup.bash && cd ~/ &&\
    mkdir -p ~/ros2_ws/src &&\
    cd ~/ros2_ws/src &&\
    ros2 pkg create --build-type ament_python embedded_mas_examples --dependencies std_msgs rclpy &&\
    mkdir -p ~/ros2_ws/src/embedded_mas_examples/embedded_mas_examples/ && \
    cd ~/ &&\
    git clone https://github.com/embedded-mas/jason-ros-course-wesaac2024.git &&\
    cd ~/ros2_ws/src/embedded_mas_examples/embedded_mas_examples/ &&\
    cp ~/jason-ros-course-wesaac2024/resources/turtlesim-extension/setup.py ~/ros2_ws/src/embedded_mas_examples/ &&\
    cp ~/jason-ros-course-wesaac2024/resources/turtlesim-extension/energy_turtle.py ~/ros2_ws/src/embedded_mas_examples/embedded_mas_examples/ &&\
    cd ~/ros2_ws/ &&\
    colcon build &&\
    source install/setup.bash &&\
    echo "source ~/ros2_ws/install/setup.bash" >> ~/.bashrc
    rm -r ~/jason-ros-course-wesaac2024 &&\
    ros2 run embedded_mas_examples service) &\
  ( /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml")\
 )' &&\
 sleep 2 &&\
 sudo docker exec turtles_example /bin/bash -c 'source /opt/ros/humble/setup.bash && ros2 topic pub -t 1 /turtle1/energy std_msgs/msg/Int32 "{data: 1000}"' &&\
 echo -e '\e[1;33m**** Docker container is ready. Start the JaCaMo application****\e[0m'
----


windows:
docker run -d --rm --net=ros --env="DISPLAY_WIDTH=3000" --env="DISPLAY_HEIGHT=1800" --env="RUN_XTERM=no" --name=novnc -p=8080:8080 theasp/novnc:latest
Start-Sleep -Seconds 2
docker run -d --name turtles_example --rm --net=ros --env="DISPLAY=novnc:0.0" --env="ROS_MASTER_URI=http://localhost:11311" -p11311:11311 -p9090:9090 maiquelb/embedded-mas-ros2:0.5 powershell -Command "((source /opt/ros/humble/setup.bash && ros2 run _node) & (source /opt/ros/humble/setup.bash && cd ~/ && git clone https://github.com/embedded-mas/jason-ros-course-wesaac2024.git && mkdir -p ~/ros2_ws/src && cd ~/ros2_ws/src && ros2 pkg create --build-type ament_python embedded_mas_examples --dependencies std_msgs rclpy && mkdir -p ~/ros2_ws/src/embedded_mas_examples/embedded_mas_examples/ && cd ~/ros2_ws/src/embedded_mas_examples/embedded_mas_examples/ && cp ~/jason-ros-course-wesaac2024/resources/turtlesim-extension/setup.py ~/ros2_ws/src/embedded_mas_examples/ && cp ~/jason-ros-course-wesaac2024/resources/turtlesim-extension/energy_turtle.py ~/ros2_ws/src/embedded_mas_examples/embedded_mas_examples/ && cd ~/ros2_ws/ && colcon build && source install/setup.bash && rm -r ~/jason-ros-course-wesaac2024 && ros2 run embedded_mas_examples service) & (powershell -Command 'source /opt/ros/humble/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml'))"
Start-Sleep -Seconds 5
docker exec turtles_example powershell -Command "source /opt/ros/humble/setup.bash && ros2 topic pub -t 1 /turtle1/energy std_msgs/msg/Int32 '{data: 1000}'"
echo '**** DOCKER CONTAINER IS READY ****'

When the container is launched, go to link:http://localhost:8080/vnc.html[`http://localhost:8080/vnc.html`] to inspect the simulation.

== Part 1: Introduction to ROS 

=== Task 1.1: Understanding ROS Topics
* Exercise 1.1.1. The command shown below lists the avaliable topics and the data type that they record. Type it and observe the output.
----
ros2 topic list -t
----

* Exercise 1.1.2. ROS data type (also known as message types) may record complex data structures. Use the command below to check the data structure of the different data types. Replace `[data type]` by the data type to be ckecked.
----
ros2 interface show [data type]
----

* Exercise 1.1.3. Type the following command in a shell and observe the behaviour of the turtle:
----
ros2 topic pub -1 /turtle1/cmd_vel geometry_msgs/msg/Twist  "{linear: {x: 1.0, y: 1.0, z: 1.0}, angular: {x: 0.0, y: 0.0, z: 0.0}} "
----

=== Task 1.2: ROS Services
* Exercise 1.2.1. The command shown below lists the avaliable service and the data type that they request/return. Type it and observe the output.
----
ros2 service list -t
----

* Exercise 1.2.2. ROS service type define the structure of request and response data. Use the command below to check the data structure of the different service types. Replace `[service type]` by the data type to be ckecked. As a suggestion, check the type of the services `/rosapi/list_parameters` and `/turtle1/set_pen`. What are the inputs and outputs?
----
ros2 interface show [service type]
----

* Exercise 1.2.3. Type the following command in a shell and observe the behaviour of the turtle:
----
ros2 service call /turtle1/teleport_absolute turtlesim/srv/TeleportAbsolute "{x: 5.0, y: 5.0, theta: 1}"
----


== Part 2. Introduction to Jason

=== Task 2.1: Run the first JaCaMo application

Clone the repository at (https://github.com/maiquelb/jacamo-wesaac2023). Open the folder link:hands-on/part2/ex1[`hands-on/part2/ex1`] with the Visual Studio Code (or access it in the terminal).  Then, run the project by typing the command below in the terminal:

----
jacamo agents_intro.jcm 
----



=== Task 2.2: Reading and understanding agent programs

* Exercise 2.2.1: open the JaCaMo application file (link:hands-on/part2/ex1/agents_intro.jcm[`agents_intro.jcm`]) and the personal assistant agent code (file link:hands-on/part2/ex1/src/agt/personal_assistant.asl[`hands-on/part2/ex1/src/agt/personal_assistant.asl`]). Read the files and identify the beliefs, goals, and plans. Try to map the program to the observed behavior. 

* Exercise 2.2.2: open the link:http://localhost:3272/[_mind inspector_] for the agents `bob` and `marie`. Compare the beliefs there with those identified in the program. Are they the same? Are they represented the same way? 

* Exercise 2.2.3: observe the plan in lines 13--14 of the personal assistant agent code (file link:hands-on/part2/ex1/src/agt/personal_assistant.asl[`src/agt/personal_assistant.asl`]). What is the difference between this plan and the other ones?

* Exercise 2.2.4: type the command below, replacing `<agent_id>` by the identifier of an agent (either `bob` or `marie`). Observe the behaviour of the agent. Open the link:http://localhost:3272/[_mind inspector_]  and check whether the belief base of the agent has changed after running this command.

----
curl --request POST 'http://127.0.1.1:8080/agents/<agent_id>/command' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'c=-+day_of_week(sunday)'
----

=== Task 2.3: Extending the agent program
* Exercise 2.3.1: make the agent `bob` to inform the current date using the plan `inform_date`. The other agents must not give this information.

* Exercise 2.3.2: add a new personal assistant agent to the system. This agent should greet in portuguese ("Bom dia.").

* Exercise 2.3.3: set the language of bob to japanese without adding any plan. Run the system and observe the output. Handle exceptions if needed.

* Exercise 2.3.4 (communicating beliefs): change the code of bob so that, after print the greeting message, it sends a message to alice informing the current day of week. This information must have the form `day_of_week(Day)` (e.g. `day_of_week(sunday)'). Run the application and observe the output.

* Exercise 2.3.5 (getting beliefs from perception - part 1): open the JaCaMo application file (link:hands-on/part2/ex2/agents_intro.jcm[`agents_intro.jcm`]) and the personal assistant agent code (file link:hands-on/part2/ex2/src/agt/personal_assistant.asl[`src/agt/personal_assistant.asl`]). Go to the link:http://localhost:3272/[_mind inspector_] and observe the beliefs of agents `bob` and `marie`.

* Exercise 2.3.6 (getting beliefs from perception - part 2): make both the agents to print the clock value every 10 seconds.

* Exercise 2.3.7 (understandng goals):  in the agent code available at file link:hands-on/part2/ex2/src/agt/personal_assistant.asl[`hands-on/part2/ex2/src/agt/personal_assistant.asl`], what is the type of the `!start_clock`(declarative or procedural)?

* Exercise 2.3.7 (specifying declarative goals I): implement a new version of the MAS available at link:hands-on/part2/ex2/agents_intro.jcm[`hands-on/part2/ex2/`] including the declarative goal `clock_finished(T)`, which is to be achieved when the clock is finished after a time equal or higher to `T`. To this end, (i) add a plan to satisfy this goal in agent code (link:hands-on/part2/ex2/src/agt/personal_assistant.asl[`src/agt/personal_assistant.asl`]) and (ii) add to the agent `bob`  the goal to have the clock finished at the time 50000.

* Exercise 2.3.7 (specifying maintenance goals): make alice to print the clock value every 10 seconds.

==== Questons:
* Where to the beliefs come from?
* Where are the actions implemented?

=== Task 2.1 Understanting and programming beliefs

== Part 3: Introduction to Jason-ROS

In this tutorial, we will develop a BDI agent that moves in a square environment. This agent considers the following beliefs:

* `battery_level(L)`: the avaliable energy level in the robot's battery is `L`. When `L=0`, there is no available energy.
* `security_level(L)`: the current status environmental safety, This belief is supposed to be observed from some environmental device (e.g. an alarm).
* `position(X,Y)`: the current position of the robot in a cartesian coordinate system.

In addition, this agent has the following repertory of actions:

* `go_to(X,Y)`: the robot goes to the coordinate (X,Y).
* `move(D)`: the robot moves forward by a distance `D`.
* `rotate\(R)`: the robot rotates by an angle R (in radians) around its own axis


The cognitive portion of the agent is programmed with Jason. The body of the agent is a turtlebot running in an extended version of the link:http://wiki.ros.org/turtlesim[turtlesim simulator]. This extended simulator provides the following topics:

[cols="2,2,1", options="header"]
|===
| Topic name | Topic type | Description

| /turtleX/energy
| sts_msgs/Int32
| Records an integer value representing the battery level of the robot.

| /turtleX/alarm
| std_msgs/String
| Records a String value representing the status of an alarm that monitors the environmental safety. Possible values of this topic are `safe` and `critical`

| /turtleX/pose
| turtlesim/Pose
| Records a tuple (x, y, theta , linear_velocity, angular_velocity) where (i) `x` and `y` are the coordinates of the robot position in the cartesian coordinate system; (ii) `theta` is the angle between the robot's forward direction and the positive x-axis; (iii) `linear_velocity` is the speed at which the robot is moving in a straight line; and (iv) `angular_velocity`, is the rate of change of the robot's orientation.

| /turtleX/cmd_vel
| geometry_msgs/Twist
| Records the intended linear and angular velocity of the robot. The robot controller reads the topic and adjusts its velocity accordingly, keeping the velocity for 1 second
|===


Besides, the simulator provides the following services:
[cols="2,2,1", options="header"]
|===
| Service name | Service type | Description

| /turtleX/teleport_absolute
| turtlesim/srv/TeleportAbsolute
| Moves the robot’s to a given point (x, y ) in the environment and rotates the robot if needed

| /turtleX/teleport_relative
| /turtlesim/srv/TeleportRelative
| Moves the robot’s along a given distance forward/backward and rotates the robot if needed.
|===


=== Task 3.1: Configuring perceptions

* Exercise 3.1.1. Run the JaCaMo application at link:https://github.com/embedded-mas/jason-ros-course-wesaac2024/tree/main/hands-on/part3/ex1[`part3/ex1`]. Check the beliefs of the agent `robot1` in the mind inspector available at link:http://127.0.1.1:3272/[http://127.0.1.1:3272]. Analyze the relations between the agent's beliefs and the file configurations in the file  link:https://github.com/embedded-mas/jason-ros-course-wesaac2024/blob/main/hands-on/part3/ex1/src/agt/robot1.yaml[`src/agt/robot1.yaml`]

* Exercise 3.1.2. In the same application from the previous exerise, the file link:https://github.com/embedded-mas/jason-ros-course-wesaac2024/blob/main/hands-on/part3/ex1/src/agt/ros_agent.asl[`src/agt/ros_agent.asl`] is the source code of an agent that simply prints its battery level. Extend this implementation to print the current environmental safety status when it changes. The agent records this information in the belief `security_level(L)`.

* Exercise 3.1.3. Extend the code of the agent of to print its current position (X,Y) when it changes. The agent records this information in the belief `position(X,Y)`. To test the position changing, move the robot with the following command:
```
ros2 topic pub -1 /turtle1/cmd_vel geometry_msgs/msg/Twist  "{linear: {x: 1.0, y: 1.0}} "
```

=== Task 3.2: Configuring actions

The actions of the agents can be concretely carried out through topic writing and service requests. The effectors of the robot are controlled by the topic `/turtleX/cmd_vel` and by the services `turtleX/teleport_absolute` and `/turtleX/teleport_relative`.

== Part 4: Advancing on Jason-ROS

=== Implementing complex behaviours
=== Programming multi-robot systems
=== Customizing internal actions
